import org.junit.Test;
import static org.junit.Assert.*;

/**
 * This Java source file was auto generated by running 'gradle init --type
 * java-library' by 'chris' at '9/21/16 7:56 PM' with Gradle 3.1
 *
 * @author chris, @date 9/21/16 7:56 PM
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
