/**
 * This Java source file was auto generated by running 'gradle buildInit --type
 * java-library' by 'chris' at '9/21/16 7:56 PM' with Gradle 3.1
 *
 * @author chris, @date 9/21/16 7:56 PM
 */
public class Library {
	/**
	 * 
	 * @return jalla jalla
	 */
	@SuppressWarnings("static-method")
	public boolean someLibraryMethod() {
		return true;
	}
}
